apiVersion: 1

datasources:
  - name: Wandrail PostgreSQL
    type: postgres
    uid: wandrail_pg
    url: tourisme_postgres:5432
    user: postgres
    secureJsonData:
      password: "00000"
    jsonData:
      database: tourisme_train
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
